---
fixtures:
  forge_modules:
    ruby_task_helper: "puppetlabs/ruby_task_helper"
    service: "puppetlabs/service"
    package: "puppetlabs/package"
    reboot: "puppetlabs/reboot"
  repositories:
    cron_core: 'https://github.com/puppetlabs/puppetlabs-cron_core'
    provision: 'https://github.com/puppetlabs/provision'
    bootstrap: 'https://github.com/puppetlabs/puppetlabs-bootstrap'
    puppet_conf: 'https://github.com/puppetlabs/puppetlabs-puppet_conf'
    deploy_pe: 'https://github.com/jarretlavallee/puppet-deploy_pe'
    ruby_task_helper: 'https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib' 
    facts: 'https://github.com/puppetlabs/puppetlabs-facts'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    node_manager: 'https://github.com/WhatsARanjit/puppet-node_manager'
    apply_helpers: 'https://github.com/puppetlabs/puppetlabs-apply_helpers'
    bolt_shim: 'https://github.com/puppetlabs/puppetlabs-bolt_shim'
    debug: 'https://github.com/nwops/puppet-debug'
    format: 'https://github.com/voxpupuli/puppet-format'
    container_inventory: 'https://gitlab.com/nwops/bolt-container_inventory'
    peadm: 'https://github.com/puppetlabs/puppetlabs-peadm.git'
  symlinks:
    peadm_spec: 'peadm/spec/acceptance/peadm_spec/'